import { test, expect } from '@playwright/test';
import { existsSync, readFileSync } from 'node:fs';
import { type Address } from 'viem';
import { injectedWallet, LIVE_URL } from './wallet';
const info=existsSync('local-deployment.json')?JSON.parse(readFileSync('local-deployment.json','utf8')) as {customer:Address;merchant:Address;vault:Address}:undefined;
test.skip(!info,'Requires local Anvil deployment.');
test('customer signs, separate merchant submits, captures14 and releases6',async({page})=>{
 await injectedWallet(page,info!);await page.goto(LIVE_URL+'/#playground');
 await page.getByRole('button',{name:'Connect wallet',exact:true}).click();await page.getByRole('button',{name:'Switch network',exact:true}).click();
 await page.getByRole('button',{name:'Approve 100 USDG',exact:true}).click();await expect(page.getByRole('button',{name:'Deposit USDG',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Deposit USDG',exact:true}).click();
 await expect(page.getByRole('button',{name:'Authorize hold',exact:true})).toBeEnabled();
 await page.getByText('Customer-signed authorization',{exact:true}).click();
 const availableBefore=await page.locator('.balance-metric').first().locator('strong').innerText();
 await page.getByRole('button',{name:'Sign authorization',exact:true}).click();
 await expect(page.getByLabel('Signed authorization JSON')).toHaveValue(/"signature"/);
 const packet=await page.getByLabel('Signed authorization JSON').inputValue();
 await expect(page.locator('.transaction-notice')).toContainText('Authorization signed');
 expect(await page.locator('.balance-metric').first().locator('strong').innerText()).toBe(availableBefore);
 await page.getByRole('button',{name:'Merchant',exact:true}).click();
 await page.evaluate(()=>{(window as unknown as {covaSetWallet:(s:string)=>void}).covaSetWallet('merchant');});
 await page.getByLabel('Customer authorization JSON').fill(packet);
 await expect(page.getByRole('button',{name:'Submit authorization',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Submit authorization',exact:true}).click();
 await expect(page.locator('.active-hold').first()).toBeVisible();
 await page.getByRole('button',{name:'Capture 14 USDG',exact:true}).first().click();await expect(page.locator('.active-hold .remaining-amount').first()).toContainText('6');
 await page.getByRole('button',{name:'Release remaining',exact:true}).first().click();
 await expect(page.locator('.settled-hold').first()).toContainText('14 USDG settled to the merchant. 6 USDG returned to the customer.');
 await page.locator('.settled-hold').first().getByText('Authorization details',{exact:true}).click();
 await expect(page.locator('.settled-hold').first().locator('.receipt-links')).toContainText('Capture');
 const context=await page.context().browser()!.newContext();const other=await context.newPage();
 await injectedWallet(other,info!);await other.goto(LIVE_URL+'/#playground');await other.getByRole('button',{name:'Connect wallet',exact:true}).click();await other.getByRole('button',{name:'Switch network',exact:true}).click();
 await expect(other.locator('.settled-hold').first()).toBeVisible();await other.locator('.settled-hold').first().getByText('Authorization details',{exact:true}).click();
 await expect(other.locator('.settled-hold').first().locator('.receipt-links')).toContainText('Capture');
 await expect(other.locator('.settled-hold').first().locator('.receipt-links')).toContainText('Release');
 await context.close();
});

test('signature rejection and nonce invalidation preserve funds and wallet ownership',async({page})=>{
 await injectedWallet(page,info!);await page.goto(LIVE_URL+'/#playground');
 await page.getByRole('button',{name:'Connect wallet',exact:true}).click();await page.getByRole('button',{name:'Switch network',exact:true}).click();
 await page.locator('#deposit-amount').fill('20');await page.getByRole('button',{name:'Approve 20 USDG',exact:true}).click();await expect(page.getByRole('button',{name:'Deposit USDG',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Deposit USDG',exact:true}).click();
 await page.getByText('Customer-signed authorization',{exact:true}).click();
 await expect(page.getByRole('button',{name:'Sign authorization',exact:true})).toBeEnabled();
 const before=await page.locator('.balance-metric').first().locator('strong').innerText();
 await page.evaluate(()=>{(window as unknown as {covaRejectNext:()=>void}).covaRejectNext();});
 await page.getByRole('button',{name:'Sign authorization',exact:true}).click();
 await expect(page.locator('.transaction-notice.failed')).toContainText('Wallet request rejected');
 await page.getByRole('button',{name:'Sign authorization',exact:true}).click();
 await expect(page.getByLabel('Signed authorization JSON')).toHaveValue(/"signature"/);
 const stale=await page.getByLabel('Signed authorization JSON').inputValue();
 await page.evaluate(()=>{(window as unknown as {covaSetWallet:(s:string)=>void}).covaSetWallet('merchant');});
 await expect(page.getByLabel('Signed authorization JSON')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Invalidate pending signatures',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Invalidate pending signatures',exact:true}).click();
 await expect(page.locator('.transaction-notice.confirmed')).toBeVisible();
 await page.evaluate(()=>{(window as unknown as {covaSetWallet:(s:string)=>void}).covaSetWallet('customer');});
 await expect(page.getByLabel('Signed authorization JSON')).toHaveValue(stale);
 await expect(page.getByRole('button',{name:'Invalidate pending signatures',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Invalidate pending signatures',exact:true}).click();
 await expect(page.getByLabel('Signed authorization JSON')).toHaveCount(0);
 await expect(page.locator('.balance-metric').first().locator('strong')).toHaveText(before);
 await page.getByRole('button',{name:'Merchant',exact:true}).click();
 await page.evaluate(()=>{(window as unknown as {covaSetWallet:(s:string)=>void}).covaSetWallet('merchant');});
 await page.getByLabel('Customer authorization JSON').fill(stale);
 await expect(page.getByRole('button',{name:'Submit authorization',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Submit authorization',exact:true}).click();
 await expect(page.locator('.transaction-notice.failed')).toContainText('nonce is stale');
 await expect(page.locator('.active-hold')).toHaveCount(0);
});
