import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createPublicClient, createWalletClient, erc20Abi, http, keccak256, parseUnits, toHex, decodeEventLog, type Address, type Hash } from 'viem';
import { foundry } from 'viem/chains';
import { mnemonicToAccount } from 'viem/accounts';
import { vaultAbi } from '../lib/abi';
import { readSnapshot, verifyDeployment } from '../lib/chain';
const info=JSON.parse(readFileSync('local-deployment.json','utf8')) as {token:Address;vault:Address};
const mnemonic='test test test test test test test test test test test junk';
const customer=mnemonicToAccount(mnemonic,{addressIndex:0});const merchant=mnemonicToAccount(mnemonic,{addressIndex:1});
const rpc=process.env.COVA_LOCAL_RPC_URL || 'http://127.0.0.1:8545';const client=createPublicClient({chain:foundry,transport:http(rpc)});
if(await client.getChainId()!==31337) throw new Error('Integration test only supports local Anvil.');
const customerWallet=createWalletClient({account:customer,chain:foundry,transport:http(rpc)});
const merchantWallet=createWalletClient({account:merchant,chain:foundry,transport:http(rpc)});
const units=(value:string)=>parseUnits(value,6);
const config={local:true,demo:false,chainId:31337 as const,rpc,token:info.token,vault:info.vault};
assert.equal((await verifyDeployment(client,config)).decimals,6);
const receipts:Record<string,Hash>={};
async function confirmed(name:string,hash:Hash) {const receipt=await client.waitForTransactionReceipt({hash});assert.equal(receipt.status,'success',name);receipts[name]=hash;return receipt;}
const initial=await readSnapshot(client,config,customer.address);
const merchantStart=await client.readContract({address:info.token,abi:erc20Abi,functionName:'balanceOf',args:[merchant.address]});
await confirmed('approve',await customerWallet.writeContract({address:info.token,abi:erc20Abi,functionName:'approve',args:[info.vault,units('100')]}));
await confirmed('deposit',await customerWallet.writeContract({address:info.vault,abi:vaultAbi,functionName:'deposit',args:[units('100')]}));
let state=await readSnapshot(client,config,customer.address);assert.equal(state.available,initial.available+units('100'));
const now=(await client.getBlock()).timestamp;
const receipt=await confirmed('authorize',await customerWallet.writeContract({address:info.vault,abi:vaultAbi,functionName:'createHold',args:[merchant.address,units('20'),now+3600n,keccak256(toHex('Court Booking'))]}));
let id:Hash|undefined;
for(const log of receipt.logs) {try {const event=decodeEventLog({abi:vaultAbi,data:log.data,topics:log.topics,eventName:'HoldCreated'});id=event.args.holdId;} catch {}}
assert.ok(id,'HoldCreated receipt contains the hold id');
state=await readSnapshot(client,config,customer.address);assert.equal(state.available,initial.available+units('80'));assert.equal(state.reserved,initial.reserved+units('20'));
await assert.rejects(client.simulateContract({address:info.vault,abi:vaultAbi,functionName:'withdraw',args:[state.available+1n],account:customer.address}));
await assert.rejects(client.simulateContract({address:info.vault,abi:vaultAbi,functionName:'capture',args:[id,units('14')],account:customer.address}));
await assert.rejects(client.simulateContract({address:info.vault,abi:vaultAbi,functionName:'release',args:[id],account:customer.address}));
await confirmed('capture',await merchantWallet.writeContract({address:info.vault,abi:vaultAbi,functionName:'capture',args:[id,units('14')]}));
assert.equal(await client.readContract({address:info.token,abi:erc20Abi,functionName:'balanceOf',args:[merchant.address]}),merchantStart+units('14'));
await confirmed('release',await merchantWallet.writeContract({address:info.vault,abi:vaultAbi,functionName:'release',args:[id]}));
state=await readSnapshot(client,config,customer.address);assert.equal(state.available,initial.available+units('86'));assert.equal(state.reserved,initial.reserved);
const settled=state.customerHolds.find(h=>h.id===id)!;assert.equal(settled.status,3);assert.equal(settled.capturedAmount,units('14'));assert.equal(settled.customerAvailable,state.available);
await assert.rejects(client.simulateContract({address:info.vault,abi:vaultAbi,functionName:'capture',args:[id,1n],account:merchant.address}));
await confirmed('withdraw',await customerWallet.writeContract({address:info.vault,abi:vaultAbi,functionName:'withdraw',args:[units('86')]}));
state=await readSnapshot(client,config,customer.address);assert.equal(state.available,initial.available);
const tokenBalance=await client.readContract({address:info.token,abi:erc20Abi,functionName:'balanceOf',args:[info.vault]});
assert.equal(tokenBalance,await client.readContract({address:info.vault,abi:vaultAbi,functionName:'totalLiability'}));
console.log(JSON.stringify({network:'Local Anvil',success:true,flow:'100 deposit -> 20 reserve -> 14 merchant transfer -> 6 release -> 86 withdraw',holdId:id,receipts},null,2));
